### ISSUE TITLE
Fix branches

### ISSUE THREAD

**Issue by johndavis92790** [dcarteciano/travel-buddy#6]
Dangit, I totally setup the api-tests branch as the default branch, I did not mean to do that haha. I created the develop branch and the api-tests branch before I committed and pushed the main branch. I need @dcarteciano to go in and change the default branch to the main branch since its your repository. You can even delete every branch other than the main branch. Don't worry about the files, I backed them up somewhere else. Use this link for instructions on how to do this:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by dcarteciano** [comment]
I got the default branched switched to the main branch
